modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"

[[mods]] #mandatory
modId = "create_radar" #mandatory
version = "0.3" #mandatory
displayName = "Create: Radars" #mandatory
authors = "HappySG, CeoOfGoogle, Kipti, OndatraCZE, Ray(furuochen)" #optional

# The description text for the radar (multi line!) (#mandatory)
description = '''Welcome to Create Radars, a mod offering a variety of tools and blocks for Surveillance, Detection, and Controlling Weapons.'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.create_radar]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "create"
mandatory = true
versionRange = "[6.0.8,6.1.0)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "createbigcannons"
mandatory = false
versionRange = "[5.10.1,)"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.create_radar]]
modId = "valkyrienskies"
mandatory = false
versionRange = "[2.4.7,)"
ordering = "BEFORE"
side = "BOTH"
